<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5014e645192b6afbdb2d64bcf9c3d35f
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'M' => 
        array (
            'MangoPay\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'MangoPay\\' => 
        array (
            0 => __DIR__ . '/..' . '/mangopay/php-sdk-v2/MangoPay',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5014e645192b6afbdb2d64bcf9c3d35f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5014e645192b6afbdb2d64bcf9c3d35f::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
